openapi: 3.0.0
info:
  title: API сервер для проекта "Шесть городов".
  description: |-
    * Список ресурсов и маршрутов сервера "Шесть городов."
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0

tags:
  - name: offers
    description: Действия с предложениями.
  - name: users
    description: Действия с пользователем.
  - name: comments
    description: Действия с комментариями.

paths:
  /offers:
    get:
      tags:
        - offers
      summary: Получение списка предложений по аренде
      description: Получает список предложений по аренде
      responses:
        "200":
          description: Получение списка предложений.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offersList'
        "400":
          description: 'Список предложений недоступен: ошибка запроса.'
        "404":
          description: 'Список предложений недоступен: данные не найдены.'
    post:
      tags:
        - offers
      summary: Создание нового предложения
      description: Создает новое предложение по аренде
      requestBody:
        description: Информация для создания нового предложения
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
        required: true
      responses:
        "201":
          description: Предложение создано. Объект предложения.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "401":
          description: 'Предложение не может быть создано: пользователь не авторизован.'
        "400":
          description: 'Предложение не может быть создано: ошибка валидации.'
        "404":
          description: 'Предложение не может быть создано: данные не найдены.'
        "409":
          description: Предложение уже существует.

  /offers/{offerId}:
    put:
      tags:
        - offers
      summary: Редактирование предложения
      description: Редактирует предложение по аренде
      requestBody:
        description: Информация для редактирования предложения
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateOffer'
        required: true
      responses:
        "200":
          description: Предложение успешно отредактировано.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "400":
          description: 'Предложение не может быть отредактировано: ошибка запроса.'
        "403":
          description: 'Предложение не может быть отредактировано: у пользователя нет права доступа к объекту.'
        "401":
          description: 'Предложение не может быть отредактировано: пользователь не авторизован.'
        "404":
          description: 'Предложение не может быть отредактировано: данные не найдены.'
    delete:
      tags:
        - offers
      summary: Удаление предложения
      description: Удаляет предложение по аренде
      responses:
        "204":
          description: Предложение успешно удалено.
        "400":
          description: 'Предложение не может быть удалено: ошибка запроса.'
        "403":
          description: 'Предложение не может быть удалено: у пользователя нет прав доступа к объекту.'
        "401":
          description: 'Предложение не может быть удалено: пользователь не авторизован.'
        "404":
          description: 'Предложение не может быть удалено: данные не найдены.'
    get:
      tags:
        - offers
      summary: Получение детальной информации о предложении
      description: Получает детальную информации о предложении по аренде
      responses:
        "200":
          description: Получение детальной информации о предложении.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "400":
          description: 'Детальная информация о предложении недоступна: ошибка запроса.'
        "404":
          description: 'Детальная информация о предложении недоступна: данные не найдены.'

  /offers/favorites:
    get:
      tags:
        - offers
      summary: Получение списка избранных предложений по аренде
      description: Получает список избранных предложений по аренде
      responses:
        "200":
          description: Получение списка избранных предложений.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offersList'
        "400":
          description: 'Список избранных предложений недоступен: ошибка запроса.'
        "404":
          description: 'Список избранных предложений недоступен: данные не найдены.'

  /offers/premium:
    get:
      tags:
        - offers
      summary: Получение списка премиальных предложений по аренде
      description: Получает список премиальных предложений по аренде
      responses:
        "200":
          description: Получение списка премиальных предложений.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offersList'
        "400":
          description: 'Список премиальных предложений недоступен: ошибка запроса.'
        "404":
          description: 'Список премиальных предложений недоступен: данные не найдены.'

  /users/login:
    post:
      tags:
        - users
      summary: Вход в закрытую часть приложения.
      description: Возвращает токен авторизации пользователя.
      requestBody:
        description: Информация для входа в закрытую часть приложения
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginUser'
        required: true
      responses:
        "200":
          description: Пользователь авторизован. Токен пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userToken'
        "400":
          description: 'Информация об авторизации недоступна: ошибка запроса.'
        "401":
          description: 'Информация об авторизации недоступна: логин или пароль неверный или пользователь не существует.'
        "404":
          description: 'Информация об авторизации недоступна: данные не найдены.'
    get:
      tags:
        - users
      summary: Проверка состояния пользователя.
      description: Возвращает информацию об состоянии авторизации пользователя.
      responses:
        "200":
          description: Получение информациии об авторизации пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "400":
          description: 'Информация об авторизации недоступна: ошибка запроса.'
        "404":
          description: 'Информация об авторизации недоступна: данные не найдены.'

  /users/logout:
    delete:
      tags:
        - users
      summary: Выход из закрытой части приложения.
      description: Завершает пользовательский сеанс.
      responses:
        "204":
          description: Пользовательcкий сеанс завершен.
        "400":
          description: 'Пользовательский сеанс не может быть завершен: ошибка запроса.'
        "401":
          description: 'Пользовательский сеанс не может быть завершен: пользователь не авторизован.'
        "404":
          description: 'Пользовательский сеанс не может быть завершен: данные не найдены.'

  /users/signin:
    post:
      tags:
        - users
      summary: Создание нового пользователя.
      description: Создает нового пользователя.
      requestBody:
        description: Информация для создания нового пользователя
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true
      responses:
        "201":
          description: Новый пользователь создан. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: 'Новый пользователь не может быть создан: пользователь с таким email уже существует.'
        "400":
          description: 'Новый пользователь не может быть создан: ошибка валидации.'
        "401":
          description: 'Новый пользователь не может быть создан: пользователь уже авторизован.'
        "404":
          description: 'Новый пользователь не может быть создан: данные не найдены.'

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузка аватара пользователя.
      description: Загружает изображение (аватар) пользователя в формате 'png' или 'jpg'.
      responses:
        "200":
          description: Аватар пользователя успешно загружен.
        "400":
          description: 'Аватар не может быть загружен: ошибка запроса.'

  /comments/{offerId}:
    get:
      tags:
        - comments
      summary: Получение списка комментариев для предложения
      description: Возвращает список комментариев для предложения
      responses:
        "200":
          description: Получение списка комментариев.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commentsList'
        "400":
          description: 'Список предложений недоступен: ошибка запроса.'
        "404":
          description: 'Список предложений недоступен: данные не найдены.'
    post:
      tags:
        - comments
      summary: Добавление комментария для предложения
      description: Добавляет новый комментарий для предложения
      requestBody:
        description: Информация для создания нового комментария
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createComment'
        required: true
      responses:
        "201":
          description: Комментарий создан. Объект комментария.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
        "401":
          description: 'Комментарий не может быть создан: пользователь не авторизован.'
        "400":
          description: 'Комментарий не может быть создан: ошибка валидации.'
        "404":
          description: 'Комментарий не может быть создан: данные не найдены.'
        "409":
          description: Комментарий уже существует.


components:
  schemas:
    createUser:
      type: object
      properties:
        email:
          type: string
          example: keks@keks.com
        avatarURL:
          type: string
          example: https://www.domain.com/image.png
        name:
          type: string
          example: Keks
        password:
          type: string
          example: 123456
        userType:
          type: string
          enum: [pro, standard]
          example: standard
    createOffer:
      type: object
      properties:
        title:
          type: string
          example: Lorem ipsum dolor sit amet.
        description:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        offerDate:
          type: string
          format: date-time
          example: 01/01/2023T12:23:34.843Z
        city:
          type: string
          enum: [Paris, Amsterdam, Cologne, Brussels, Dusseldorf, Hamburg]
          example: Amsterdam
        previewImageURL:
          type: string
          example: https://www.domain.com/image.png
        images:
          type: array
          items:
            type: string
          example: [https://www.domain.com/image1.png, https://www.domain.com/image.jpg', https://www.domain.com/image3.png]
        isPremium:
          type: boolean
          example: true
        isFavorite:
          type: boolean
          example: false
        rating:
          type: number
          example: 3
        type:
          type: string
          enum: [apartment, house, room, hotel]
          example: house
        bedrooms:
          type: number
          example: 1
        maxAdults:
          type: number
          example: 3
        price:
          type: number
          example: 1000
        goods:
          type: array
          items:
            type: string
            enum: [Breakfast, Air conditioning, Laptop friendly workspace, Baby seat, Washer, Towels, Fridge]
          example: [Breakfast, Air conditioning]
        hostId:
          type: string
          example: sdfsdf2343sdfsdfs
        reviews:
          type: number
          example: 12
        coordinates:
          type: array
          items:
            type: number
          example: [52.370216, 4.895168]
    updateOffer:
      type: object
      properties:
        title:
          type: string
          example: Lorem ipsum dolor sit amet.
        description:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        offerDate:
          type: string
          format: date-time
          example: 01/01/2023T12:23:34.843Z
        city:
          type: string
          enum: [Paris, Amsterdam, Cologne, Brussels, Dusseldorf, Hamburg]
          example: Amsterdam
        previewImageURL:
          type: string
          example: https://www.domain.com/image.png
        images:
          type: array
          items:
            type: string
          example: [https://www.domain.com/image1.png, https://www.domain.com/image.jpg', https://www.domain.com/image3.png]
        isPremium:
          type: boolean
          example: true
        isFavorite:
          type: boolean
          example: false
        rating:
          type: number
          example: 3
        type:
          type: string
          enum: [apartment, house, room, hotel]
          example: house
        bedrooms:
          type: number
          example: 1
        maxAdults:
          type: number
          example: 3
        price:
          type: number
          example: 1000
        goods:
          type: array
          items:
            type: string
            enum: [Breakfast, Air conditioning, Laptop friendly workspace, Baby seat, Washer, Towels, Fridge]
          example: [Breakfast, Air conditioning]
        hostId:
          type: string
          example: sdfsdf2343sdfsdfs
        reviews:
          type: number
          example: 12
        coordinates:
          type: array
          items:
            type: number
          example: [52.370216, 4.895168]
    user:
      type: object
      properties:
        id:
          type: string
          example: saldf23lj34ljn67
        email:
          type: string
          example: keks@keks.com
    offer:
      type: object
      properties:
        title:
          type: string
          example: Lorem ipsum dolor sit amet.
        description:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        offerDate:
          type: string
          format: date-time
          example: 01/01/2023T12:23:34.843Z
        city:
          type: string
          enum: [Paris, Amsterdam, Cologne, Brussels, Dusseldorf, Hamburg]
          example: Amsterdam
        previewImageURL:
          type: string
          example: 'https://www.domain.com/image.png'
        images:
          type: array
          items:
            type: string
          example: [https://www.domain.com/image1.png, https://www.domain.com/image.jpg', https://www.domain.com/image3.png]
        isPremium:
          type: boolean
          example: true
        isFavorite:
          type: boolean
          example: false
        rating:
          type: number
          example: 3
        type:
          type: string
          enum: [apartment, house, room, hotel]
          example: house
        bedrooms:
          type: number
          example: 1
        maxAdults:
          type: number
          example: 3
        price:
          type: number
          example: 1000
        goods:
          type: array
          items:
            type: string
            enum: [Breakfast, Air conditioning, Laptop friendly workspace, Baby seat, Washer, Towels, Fridge]
          example: [Breakfast, Air conditioning]
        hostId:
          type: string
          example: sdfsdf2343sdfsdfs
        reviews:
          type: number
          example: 12
        coordinates:
          type: array
          items:
            type: number
          example: [52.370216, 4.895168]
    offersList:
      type: array
      items:
        type: object
        properties:
          title:
            type: string
            example: Lorem ipsum dolor sit amet.
          offerDate:
            type: string
            format: date-time
            example: 01/01/2023T12:23:34.843Z
          city:
            type: string
            enum: [Paris, Amsterdam, Cologne, Brussels, Dusseldorf, Hamburg]
            example: Amsterdam
          previewImageURL:
            type: string
            example: 'https://www.domain.com/image.png'
          isPremium:
            type: boolean
            example: true
          isFavorite:
            type: boolean
            example: true
          rating:
            type: number
            example: 3
          type:
            type: string
            enum: [apartment, house, room, hotel]
            example: house
          price:
            type: number
            example: 1000
          reviews:
            type: number
            example: 12
    comment:
      type: object
      properties:
        text:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        commentDate:
          type: string
          format: date-time
          example: 01/01/2023T12:23:34.843Z
        rating:
          type: number
          example: 4
        authorId:
          type: string
          example: sdfsdf2343sdfsdfs
    createComment:
      type: object
      properties:
        text:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        commentDate:
          type: string
          format: date-time
          example: 01/01/2023T12:23:34.843Z
        rating:
          type: number
          example: 4
        authorId:
          type: string
          example: sdfsdf2343sdfsdfs
    commentsList:
      type: array
      items:
        type: object
      properties:
        text:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        commentDate:
          type: string
          format: date-time
          example: 01/01/2023T12:23:34.843Z
        rating:
          type: number
          example: 4
        authorId:
          type: string
          example: sdfsdf2343sdfsdfs
    loginUser:
      type: object
      properties:
        password:
          type: string
          example: saldf23lj34ljn67
        email:
          type: string
          example: keks@keks.com
    userToken:
      type: string
      example: saldf23lj34ljn67




