# Пользователи

## Создать нового пользователя.

POST http://localhost:4000/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "newmail@mail.com",
  "avatarURL": "string.jpg",
  "name": "Hello",
  "password": "123456",
  "userType": "standard"
}

###

## Войти в закрытую часть приложения.

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "mymail@mail.com",
  "password": "World!"
}

###

## Проверить информацию об состоянии авторизации пользователя.

GET http://localhost:4000/users/login HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im15bWFpbEBtYWlsLmNvbSIsIm5hbWUiOiJIZWxsbyIsImlkIjoiNjU0MGFjNDZiMTgzOTFiNmRlOWUwNDA1IiwiaWF0IjoxNjk4OTk2MjcwLCJleHAiOjE2OTkxNjkwNzB9.DPzAhpF1meFmWplwBo-iajxfBxfpHQidxslT7PL16SE

###

## Загрузить изображение (аватар) пользователя в формате 'png' или 'jpg'.

POST http://localhost:4000/users/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im15bWFpbEBtYWlsLmNvbSIsIm5hbWUiOiJIZWxsbyIsImlkIjoiNjU0MGFjNDZiMTgzOTFiNmRlOWUwNDA1IiwiaWF0IjoxNjk4OTk2MjcwLCJleHAiOjE2OTkxNjkwNzB9.DPzAhpF1meFmWplwBo-iajxfBxfpHQidxslT7PL16SE

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avataaars.png"
Content-Type: image/jpeg

< /Users/asus/OneDrive/Рабочий стол/avataaars.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

## Добавить/удалить предложения в/из избранное.

GET http://localhost:4000/users/favorites/6542cee20eedd04a70eb8bea HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5ld21haWxAbWFpbC5jb20iLCJuYW1lIjoiSGVsbG8iLCJpZCI6IjY1NDFmYmVlMjE4ZTc3N2NmN2YyODQyNyIsImlhdCI6MTY5ODgyMzI3NywiZXhwIjoxNjk4OTk2MDc3fQ.XfNNykJ3FobqM3NApsLRWSbgfzo67NymJ4cAn3ELATA

