#Предложения

## Получить список предложений

GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im15bWFpbEBtYWlsLmNvbSIsIm5hbWUiOiJIZWxsbyIsImlkIjoiNjU0MGFjNDZiMTgzOTFiNmRlOWUwNDA1IiwiaWF0IjoxNjk4OTk2MjcwLCJleHAiOjE2OTkxNjkwNzB9.DPzAhpF1meFmWplwBo-iajxfBxfpHQidxslT7PL16SE

###

## Создать новое предложение

POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5ld21haWx3QG1haWxjLmNvbSIsIm5hbWUiOiJIZWxsbyIsImlkIjoiNjU1MjljOGE2YTk0YTY5MjY1ZTg3NThlIiwiaWF0IjoxNjk5OTEyODg1LCJleHAiOjE3MDAwODU2ODV9.eb9aX-0eorWGEQS0NJ4gBHcaxhhr5EqqL-4yDq9XHwA

{
  "title": "This is a test21 offer",
  "description": "The location of the apartment was perfect - close to all of the major attractions, best shopping, and great restaurants. Public transit was easy from the hotel.",
  "city": "Hamburg",
  "previewImageURL": "domain.com/image.jpg",
  "images": ["img/house-03.jpg", "img/house-04.jpg", "img/house-05.jpg", "img/hotel-06.jpg", "img/room-07.jpg", "img/apartment-08.jpg"],
  "isPremium": "true",
  "type": "house",
  "bedrooms": "2",
  "maxAdults": "10",
  "price": "11111",
  "goods": ["Towels", "Fridge"],
  "coordinates": {"latitude": "51.225402", "longitude": "6.776314"}
}

###

## Загрузить изображение для предложения
POST http://localhost:4000/offers/6544e3cfd80130f711929dba/image HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im15bWFpbEBtYWlsLmNvbSIsIm5hbWUiOiJIZWxsbyIsImlkIjoiNjU0MGFjNDZiMTgzOTFiNmRlOWUwNDA1IiwiaWF0IjoxNjk4OTk2MjcwLCJleHAiOjE2OTkxNjkwNzB9.DPzAhpF1meFmWplwBo-iajxfBxfpHQidxslT7PL16SE
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="default-avatar.png"
Content-Type: image/png

< /Users/asus/OneDrive/Рабочий стол/default-avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Получение детальной информации о предложении по идентификатору

GET http://localhost:4000/offers/654b8169a502d3da7d45d8da HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im15bWFpbEBtYWlsLmNvbSIsIm5hbWUiOiJIZWxsbyIsImlkIjoiNjU0MGFjNDZiMTgzOTFiNmRlOWUwNDA1IiwiaWF0IjoxNjk5NDQyNzc4LCJleHAiOjE2OTk2MTU1Nzh9.jWYeiqYt-SfOGU8WRnJfN31cdhRM-tsW3-ofu7xDMzo

###

## Удалить предложение по идентификатору

DELETE http://localhost:4000/offers/6542cdff0eedd04a70eb8bc3 HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im15bWFpbEBtYWlsLmNvbSIsIm5hbWUiOiJIZWxsbyIsImlkIjoiNjU0MGFjNDZiMTgzOTFiNmRlOWUwNDA1IiwiaWF0IjoxNjk4OTk2MjcwLCJleHAiOjE2OTkxNjkwNzB9.DPzAhpF1meFmWplwBo-iajxfBxfpHQidxslT7PL16SE

###

## Редактировать предложение по идентификаторы

PATCH http://localhost:4000/offers/6544e3cfd80130f711929dba HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im15bWFpbEBtYWlsLmNvbSIsIm5hbWUiOiJIZWxsbyIsImlkIjoiNjU0MGFjNDZiMTgzOTFiNmRlOWUwNDA1IiwiaWF0IjoxNjk5MzQ2MzI0LCJleHAiOjE2OTk1MTkxMjR9.E8ez03VrN4msGEet-JBygzGDnJYrx1H4G-X8ijyEZGQ

{
  "price": "12345"
}

###

## Получить список премиальных предложений для определенного города

GET http://localhost:4000/offers/premium/Amsterdam HTTP/1.1

###

## Получить список избранных предложений

GET http://localhost:4000/offers/favorites HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im15bWFpbEBtYWlsLmNvbSIsIm5hbWUiOiJIZWxsbyIsImlkIjoiNjU0MGFjNDZiMTgzOTFiNmRlOWUwNDA1IiwiaWF0IjoxNjk4OTk2MjcwLCJleHAiOjE2OTkxNjkwNzB9.DPzAhpF1meFmWplwBo-iajxfBxfpHQidxslT7PL16SE

###
