# Комментарии
## Добавить новый комментарий для предложения

POST http://localhost:4000/comments/654b8169a502d3da7d45d8da HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im15bWFpbEBtYWlsLmNvbSIsIm5hbWUiOiJIZWxsbyIsImlkIjoiNjU0MGFjNDZiMTgzOTFiNmRlOWUwNDA1IiwiaWF0IjoxNjk5NDQyNzc4LCJleHAiOjE2OTk2MTU1Nzh9.jWYeiqYt-SfOGU8WRnJfN31cdhRM-tsW3-ofu7xDMzo
Content-Type: application/json

{
  "text": "Test comment6. This is test comment.",
  "rating": "3"
}

###

## Получить список комментариев для предложения

GET http://localhost:4000/comments/65200c3b1ae0b45c5492156c HTTP/1.1

###
